# Generated by Django 4.2.1 on 2023-05-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriptions',
            new_name='description',
        ),
    ]
